apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: roundrobin-mysql
  namespace: middleware
  labels:
    app: galera
    type: roundrobin
spec:
  ports:
  - port: 3306
    name: mysql
  - port: 4444
    name: sst
  - port: 4567
    name: replication
  - port: 4568
    name: ist
  clusterIP: None
  selector:
    app: galera
